#!/usr/bin/env ruby

#lib = File.expand_path(File.dirname(__FILE__) + '/../lib')
lib = File.expand_path(File.dirname(__FILE__) + 'lib')
$LOAD_PATH.unshift(lib) if File.directory?(lib) && !$LOAD_PATH.include?(lib)

require File.expand_path("../../lib/docker_app", __FILE__)
#require "docker_app"



puts "Docker app v.#{DockerApp::VERSION}"

# input
#args = ARGV.dup
#ARGV.clear
#command = args.shift.strip rescue 'help'


DockerApp::CLI.start
